### ISSUE TITLE
Lacking mutations and queries for amd's status update tracking

### ISSUE THREAD

**Issue by ivinjabraham** [amfoss/root#11]
I will need a few additional fields and mutations:

1. Streaks tied to a member: How many consecutive days they have or have not sent updates. Need both query and mutation. Also need to store the all time high streak. 
2. Query to get discord IDs and which mentor group they belong to.

I can also push anything that might be useful. Do we want to store status updates or number of updates sent in a month or something of that sort? @Wreck-X

**Comment by hkx05** [comment]
i will work on this

**Comment by Wreck-X** [comment]
@he1senbrg is already working on this, please confirm with him before you do @hkx05

**Comment by hkx05** [comment]
He said I can work on this

**Comment by he1senbrg** [comment]
@hkx05 You can work on this
